### ISSUE TITLE
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found on Bitbucket pipelines CI

### ISSUE THREAD

**Issue by s-a** [Microsoft/napajs#140]
I try to set up CI integration on bitbucket pipelines, Project compiles fine on my Machine (Windows 10)
I am a c++ noop but I feel there is an older c++ compiler version installes on bitbucket? Does anyone know how to work around this problem?

```shell
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/atlassian/pipelines/agent/build/node_modules/napajs/bin/napa-binding.node)
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/napajs/lib/binding.js:22:22)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/napajs/lib/log.js:5:15)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/napajs/lib/index.js:5:13)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/test/metabolic-device-2-data-decoder-thread.spec.js:6:12)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /opt/atlassian/pipelines/agent/build/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/opt/atlassian/pipelines/agent/build/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/opt/atlassian/pipelines/agent/build/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at runMain (/root/.node-spawn-wrap-91-c99d2e9be88d/node:68:10)
    at Function.<anonymous> (/root/.node-spawn-wrap-91-c99d2e9be88d/node:171:5)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at /root/.node-spawn-wrap-91-c99d2e9be88d/node:178:8
    at Object.<anonymous> (/root/.node-spawn-wrap-91-c99d2e9be88d/node:181:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by s-a** [comment]
Just tried 
```shell 
add-apt-repository ppa:ubuntu-toolchain-r/test && apt-get update && apt-get upgrade && apt-get dist-upgrade
bash: add-apt-repository: command not found
```

😢

**Comment by RulerOfTheCards** [comment]
This need to be written inside the bitbucket-pipelines.yml. Props to @s-a 👍  
```
image: ubuntu:16.04

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - cat /etc/*release
          - apt-get update
          - apt-get install -y software-properties-common
          - apt-get install -y libstdc++6
          - apt-get install -y curl
          - add-apt-repository ppa:ubuntu-toolchain-r/test
          - curl -sL https://deb.nodesource.com/setup_8.x | bash -
          - apt-get update
          - apt-get -y upgrade
          - apt-get -y dist-upgrade
          - apt-get install -y nodejs
          - npm install
          - npm test
```
