### ISSUE TITLE
failed to install napajs when "downloading the pre-build binaries"

### ISSUE THREAD

**Issue by bi-kai** [Microsoft/napajs#248]
comes a error when install napajs in `China`:
```
npm i --save napajs

> napajs@0.2.3 install D:\node\www\test\test-napajs\node_modules\napajs
> node scripts/install.js

info NAPA_INSTALL installing napajs...
info NAPA_INSTALL downloading the pre-build binaries...
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: unable to verify the first certificate
node-pre-gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
node-pre-gyp ERR! stack     at emitNone (events.js:106:13)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
node-pre-gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:639:8)
node-pre-gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "D:\\node\\anzhuang\\node.exe" "D:\\node\\www\\test\\test-napajs\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-buil
d=false"
node-pre-gyp ERR! cwd D:\node\www\test\test-napajs\node_modules\napajs
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
unable to verify the first certificate
WARN NAPA_INSTALL failed to download the pre-build binaries.
WARN NAPA_INSTALL will fallback to build stage.
info NAPA_INSTALL building from sources...
'cmake-js' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
WARN NAPA_INSTALL failed to build from sources.
ERR! NAPA_INSTALL failed to install napajs.
npm WARN test-napajs@1.0.0 No description
npm WARN test-napajs@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! napajs@0.2.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the napajs@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\node\anzhuang\node_cache\_logs\2018-06-25T07_16_08_248Z-debug.log
```

I think this may because I'm using a proxy. how can i and the proxy into the installing progress?

**Comment by bi-kai** [comment]
still failed in linux with proxy config in /etc/profile.

**Comment by fs-eire** [comment]
Napa.js installation script looks for a pre-built binary file that host on github.com. For Node 8.x/Windows the file is https://github.com/Microsoft/napajs/releases/download/0.2.3/napa-binding-v0.2.3-node-v57-win32-x64.tar.gz

**Comment by bi-kai** [comment]
@fs-eire hi, can i install this tar pkg manually?
