### ISSUE TITLE
failed to install napajs when "downloading the pre-build binaries" 

### ISSUE THREAD

**Issue by RyanRong** [Microsoft/napajs#251]
```
> napajs@0.2.3 install C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\napajs
> node scripts/install.js

info NAPA_INSTALL installing napajs...
info NAPA_INSTALL downloading the pre-build binaries...
[napajs] Success: "C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\napajs\bin\napa-binding.node" is installed via remote
info NAPA_INSTALL completed successfully by download.
C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\node_modules\npmlog\log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\node_modules\npmlog\log.js:57:33)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\bin\npm-cli.js:19:13
    at Object.<anonymous> (C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\bin\npm-cli.js:75:3)
child_process.js:644
    throw err;
    ^

Error: Command failed: npm --version
C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\node_modules\npmlog\log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\node_modules\npmlog\log.js:57:33)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\bin\npm-cli.js:19:13
    at Object.<anonymous> (C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\npm\bin\npm-cli.js:75:3)

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at Object.<anonymous> (C:\Users\Ryan\Desktop\fpga_demo\testTool\node_modules\napajs\scripts\install.js:72:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
npm WARN testtool@1.0.0 No description
npm WARN testtool@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! napajs@0.2.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the napajs@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ryan\AppData\Roaming\npm-cache\_logs\2018-07-17T12_41_28_197Z-debug.log
```

**Comment by fs-eire** [comment]
It looks like a issue of npmlog. Please refer to https://github.com/npm/npmlog/issues/48 for a solution.
