### ISSUE TITLE
There's no napa-binding-v0.2.3-node-v51-win32-x64.tar.gz

### ISSUE THREAD

**Issue by zhuernm** [Microsoft/napajs#252]
> napajs@0.2.3 install C:\Users\Reed\node_modules\napajs
> node scripts/install.js

info NAPA_INSTALL installing napajs...
info NAPA_INSTALL downloading the pre-build binaries...
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/Microsoft/napajs/releases/download/0.2.3/napa-binding-v0.2.3-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\Reed\node_modules\node-pre-gyp\lib\install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:191:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\Reed\node_modules\node-pre-gyp\node_modules\request\request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Reed\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\Reed\node_modules\napajs
node-pre-gyp ERR! node -v v7.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/Microsoft/napajs/releases/download/0.2.3/napa-binding-v0.2.3-node-v51-win32-x64.tar.gz
WARN NAPA_INSTALL failed to download the pre-build binaries.
WARN NAPA_INSTALL will fallback to build stage.
info NAPA_INSTALL building from sources...
'cmake-js' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
WARN NAPA_INSTALL failed to build from sources.
ERR! NAPA_INSTALL failed to install napajs.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Reed\package.json'
npm WARN Reed No description
npm WARN Reed No repository field.
npm WARN Reed No README data
npm WARN Reed No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! napajs@0.2.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the napajs@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Reed\AppData\Roaming\npm-cache\_logs\2018-07-20T01_57_31_030Z-debug.log

**Comment by zhuernm** [comment]
Node.js version is 7.9.0
npm version is 6.2.0

**Comment by zhuernm** [comment]
node.js version = 7.9.0
npm version = 6.2.0

**Comment by yangbo1983** [comment]
yes,same problem,anyone can answer?

**Comment by smildlzj** [comment]
> 'cmake-js' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

```
npm install -g cmake-js
```

**Comment by yygutn** [comment]
same problem, and i installed cmake-js in global

**Comment by yygutn** [comment]
> same problem, and i installed cmake-js in global

i resolved it by change node version

**Comment by stoefln** [comment]
same problem here

**Comment by hoverbird** [comment]
Same here :( 
macOS Mojave
node v11.7.0
npm 6.7.0

**Comment by hoverbird** [comment]
> > same problem, and i installed cmake-js in global
> 
> i resolved it by change node version

What node version worked for you?
