### ISSUE TITLE
Library not loaded: @rpath/libnapa.dylib

### ISSUE THREAD

**Issue by txssseal** [Microsoft/napajs#70]
Getting this error when trying to run a script that uses napajs.  Tested using `recursive-fibonacci` as well.

```
colton is in ~/Code/napajs/examples/tutorial/recursive-fibonacci on (branch:master)
»  node recursive-fibonacci.js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/colton/node_modules/napajs/bin/napa-binding.node, 1): Library not loaded: @rpath/libnapa.dylib
  Referenced from: /Users/colton/node_modules/napajs/bin/napa-binding.node
  Reason: image not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/colton/node_modules/napajs/lib/binding.js:5:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by txssseal** [comment]
I have installed the necessary dependencies as well

**Comment by bsharper** [comment]
Same issue here. @txssseal are you running High Sierra?

**Comment by bsharper** [comment]
@txssseal I was able to get it to work by building the module and then symlinking the built module to the global `node_modules` folder. This doesn't resolve this issue (`npm install` shouldn't install a broken module), but if you wanted to go ahead and test `napajs` now, this might do the trick.

1. Built the module using the instructions on the [build page](https://github.com/Microsoft/napajs/wiki/build-napa.js). 
2. Ran `npm link` in the directory where I built `napajs`. This symlinks the local `napajs` module to the global `node_modules` directory.
3. Changed to my project directory, and again ran `npm link` to symlink the global `napajs` module to my project's `node_modules` directory.
4. Started `node` and entered `var napa = require("napajs");`, which executed without any errors.

**Comment by ecwyne** [comment]
Same issue here. on macOS Sierra 10.12.6 (16G29)

**Comment by bsharper** [comment]
Tested this on Ubuntu and saw what appears to be the same error.

**OS**: Ubuntu 16.04.3 LTS (x64)
**Node**: v8.7.0
**Napajs** version: 0.1.3

```
node estimate-pi-in-parallel.js
module.js:653
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libnapa.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/brian/projects/napa/node_modules/napajs/lib/binding.js:5:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

**Comment by andreimavenhut** [comment]
*OS*: MacOS High Sierra (10.13)
*Node*: v8.0.0
*Napajs* version: 0.1.3

$ node test.js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/tmp/node_modules/napajs/bin/napa-binding.node, 1): Library not loaded: @rpath/libnapa.dylib
  Referenced from: /tmp/node_modules/napajs/bin/napa-binding.node
  Reason: image not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/node_modules/napajs/lib/binding.js:5:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by gdi2290** [comment]
I'm also running into the same error on osx. it would be great if there was a docker image we could use

**Comment by daiyip** [comment]
Thanks for reporting. This is tracked by #80
