### ISSUE TITLE
Issue running on OSX 10.12.5

### ISSUE THREAD

**Issue by rashoodkhan** [Microsoft/napajs#76]
Running Node 6.11.2 and getting the following error

```node
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/rashid/Yellow-Messenger/node-threded/node_modules/napajs/bin/napa-binding.node, 1): Library not loaded: @rpath/libnapa.dylib
  Referenced from: /Users/rashid/Yellow-Messenger/node-threded/node_modules/napajs/bin/napa-binding.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rashid/Yellow-Messenger/node-threded/node_modules/napajs/lib/binding.js:5:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)```

**Comment by wcharczuk** [comment]
you have to cd into `node_modules/napajs` and `npm install --no-fetch` there. make sure you have cmake, `npm install -g cmake-js` and a local c++ toolchain

**Comment by daiyip** [comment]
Duplicated: https://github.com/Microsoft/napajs/issues/70
