### ISSUE TITLE
`GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by tigercosmos** [Microsoft/napajs#93]
follow the steps in `estimate-pi-in-parallel`
testes in ubuntu 16.04

```
$ node estimate-pi-in-parallel.js
module.js:653
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/tigercosmos/Desktop/napajs/examples/tutorial/estimate-pi-in-parallel/node_modules/napajs/bin/libnapa.so)
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/tigercosmos/Desktop/napajs/examples/tutorial/estimate-pi-in-parallel/node_modules/napajs/lib/binding.js:5:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

**Comment by helloshuangzi** [comment]
@tigercosmos Please refer [this problem](https://github.com/Microsoft/napajs/wiki/FAQ#q-i-run-the-command-npm-install-napajs-why-it-fails-with-following-message-1) in FAQ

**Comment by helloshuangzi** [comment]
[This stackoverflow page](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error) also resolved this problem.

>Basically, just do the following commands: Firstly, install:
>**sudo apt-get install libstdc++6**
This should already be installed by default, but try it anyway. If it doesn't solve it, just do the following:
>**sudo add-apt-repository ppa:ubuntu-toolchain-r/test**
>**sudo apt-get update**
>**sudo apt-get upgrade**
>**sudo apt-get dist-upgrade**

**Comment by tigercosmos** [comment]
I see. Shall we add note on README? As user would probably follow by the README and believe it will work.

**Comment by daiyip** [comment]
FAQ is added to README via #97
